@host=http://localhost:5001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImVtYWlsIjoiYW1pY2hhaUBtYW50aW5iYW5kLmNvbSIsImlkIjoiZDQwZGIzYWQtODA3Yy00MzIwLWEwMjQtZGI0ZDczMTZlMDI5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJwZXJtaXNzaW9ucyI6WyJjcmVhdGU6cmVtaW5kZXIiLCJkaXNtaXNzOnJlbWluZGVyIl0sImV4cCI6MTcwMTgwNjU2OSwiaXNzIjoiUmVtaW5kZXJTZXJ2aWNlIiwiYXVkIjoiUmVtaW5kZXJTZXJ2aWNlIn0.2VHVSWv0If8-376zADtSFB2jyec5m__cQ_-xMwP9vDs

POST {{host}}/reminders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "text": "let's do it",
    "dateTime": "2023-12-26"
}